/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/app/Header/Header.vue')['default']
    IpForm: typeof import('./src/components/Main/Forms/IpForm.vue')['default']
    IpSearch: typeof import('./src/components/Main/Table/IpSearch.vue')['default']
    IpTable: typeof import('./src/components/Main/Table/IpTable.vue')['default']
    MainButton: typeof import('./src/components/ui/Buttons/MainButton.vue')['default']
    MainContainer: typeof import('./src/components/ui/Containers/MainContainer.vue')['default']
    Mainicon: typeof import('./src/components/ui/Icon/Mainicon.vue')['default']
    MainIcon: typeof import('./src/components/ui/Icon/MainIcon.vue')['default']
    MainTextArea: typeof import('./src/components/ui/Inputs/MainTextArea.vue')['default']
    NavigationList: typeof import('./src/components/app/Header/NavigationList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/app/Header/Search.vue')['default']
  }
}
